parameters:
    open_orchestra_elastica.mapper.form.class: OpenOrchestra\Elastica\Mapper\FormToElasticaTypeMapper

services:
    open_orchestra_elastica.mapper.form:
        class: %open_orchestra_elastica.mapper.form.class%